@endpoint=http://localhost:5000/api/v1/auth
@numero=1
@stringa=zdrt
@data="2020-01-01"
@userId=66f52abc77d18cc5cc69166e
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNTI0NTEzNjZhMTc3ZTIzYTBhNjhmIiwiaWF0IjoxNzI3NjA2MzUyLCJleHAiOjE3MjgyMTExNTJ9.t3YpJpXQKY-WupO_CRZRFrBWb9EOJ9x3kuNyFxthG24

### /me
GET {{endpoint}}/me
Authorization: {{token}}

### /login mail + password
POST {{endpoint}}/login
Content-Type: application/json

{
  "email": "{{stringa}}@{{stringa}}.{{stringa}}",
  "password": "{{stringa}}{{stringa}}"
}

### /register mail + password
POST {{endpoint}}/register
Content-Type: application/json

{
  "name": "{{stringa}}",
  "surname": "{{stringa}}",
  "email": "{{stringa}}@{{stringa}}.{{stringa}}",
  "password": "{{stringa}}{{stringa}}",
  "passwordConfirm": "{{stringa}}{{stringa}}",
  "avatar": "",
  "favoriteTheme": "dark",
  "verifiedAt": {{data}}
}