@endpoint=http://localhost:5000/api/v1/category
@numero=1
@stringa="casa carut SETT vot"
@data="2020-01-01"
@categoryId=66f530c1d82782a795bf9fbf
@userId=66f52451366a177e23a0a68f
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNTI0NTEzNjZhMTc3ZTIzYTBhNjhmIiwiaWF0IjoxNzI3NjA2MzUyLCJleHAiOjE3MjgyMTExNTJ9.t3YpJpXQKY-WupO_CRZRFrBWb9EOJ9x3kuNyFxthG24

### GET http://localhost:5000/api/v1//categories recuperare una o tutte le categorie
GET {{endpoint}}
Authorization: {{token}}

### POST http://localhost:5000/api/v1/category creare una nuova categoria
POST {{endpoint}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": {{stringa}},
  "user": "{{userId}}",
  "type": "in",
  "description": {{stringa}}
}

### PUT http://localhost:5000/api/v1/user/:userId/category/:categoryId modificare una categoria
PUT {{endpoint}}/{{categoryId}}
Content-Type: application/json
Authorization: {{token}}

{
  "type": "out"
}

### DELETE http://localhost:5000/api/v1/user/:userId/category/:categoryId eliminare una categoria
DELETE {{endpoint}}/{{categoryId}}
Authorization: {{token}}