@endpoint=http://localhost:5000/api/v1/category
@numero=1
@stringa="casa carut SETT vot"
@data="2020-01-01"
@categoryId=66f530c1d82782a795bf9fbf
@userId=66f52abc77d18cc5cc69166e
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNTJhYmM3N2QxOGNjNWNjNjkxNjZlIiwiaWF0IjoxNzI3MzQ1ODY5LCJleHAiOjE3Mjc5NTA2Njl9.g5GghMyxFBKme5uvuzRcz3lwJzDDJ3C9hu9PT1Jrrig

### GET http://localhost:5000/api/v1//categories recuperare una o tutte le categorie
GET {{endpoint}}
Authorization: {{token}}

### POST http://localhost:5000/api/v1/category creare una nuova categoria
POST {{endpoint}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": {{stringa}},
  "user": "{{userId}}",
  "type": "in",
  "description": {{stringa}}
}

### PUT http://localhost:5000/api/v1/user/:userId/category/:categoryId modificare una categoria
PUT {{endpoint}}/{{categoryId}}
Content-Type: application/json
Authorization: {{token}}

{
  "type": "out"
}

### DELETE http://localhost:5000/api/v1/user/:userId/category/:categoryId eliminare una categoria
DELETE {{endpoint}}/{{categoryId}}
Authorization: {{token}}