@endpoint=http://localhost:5000/api/v1/paymentMethod
@paymentMethodId=66f419b544f6d7cf934206b2
@userId=66f44a34ad39887eb4f75546
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNDRhMzRhZDM5ODg3ZWI0Zjc1NTQ2IiwiaWF0IjoxNzI3Mjg1ODUwLCJleHAiOjE3MjcyOTY2NTB9._NI7zuZ4BC9C6Csaw7HRojf7A8kHLm2HNZ_9VZxdtiM

### GET http://localhost:5000/api/v1/paymentMethods recuperare uno o tutti i metodi di pagamento
GET {{endpoint}}
Authorization: {{token}}

### POST http://localhost:5000/api/v1/paymentMethod creare un nuovo metodo di pagamento
POST {{endpoint}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Carta di credito",
  "user": "{{userId}}",
  "type": "creditCard",
  "description": "Carta di credito",
  "initialBalance": 0
}

### PUT http://localhost:5000/api/v1/paymentMethod/:paymentMethodId modificare un metodo di pagamento
PUT {{endpoint}}/{{paymentMethodId}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Carta di debito",
  "type": "debitCard"
}

### DELETE http://localhost:5000/api/v1/paymentMethod/:paymentMethodId eliminare un metodo di pagamento
DELETE {{endpoint}}/{{paymentMethodId}}
Authorization: {{token}}