@endpoint=http://localhost:5000/api/v1/paymentMethod
@paymentMethodId=66f5351d6cd998b7161eadb8
@userId=66f52abc77d18cc5cc69166e
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNTJhYmM3N2QxOGNjNWNjNjkxNjZlIiwiaWF0IjoxNzI3MzQ1ODY5LCJleHAiOjE3Mjc5NTA2Njl9.g5GghMyxFBKme5uvuzRcz3lwJzDDJ3C9hu9PT1Jrrig

### GET http://localhost:5000/api/v1/paymentMethods recuperare uno o tutti i metodi di pagamento
GET {{endpoint}}
Authorization: {{token}}

### POST http://localhost:5000/api/v1/paymentMethod creare un nuovo metodo di pagamento
POST {{endpoint}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Carta di credito",
  "user": "{{userId}}",
  "type": "creditCard",
  "description": "Carta di credito",
  "initialBalance": 0
}

### PUT http://localhost:5000/api/v1/paymentMethod/:paymentMethodId modificare un metodo di pagamento
PUT {{endpoint}}/{{paymentMethodId}}
Content-Type: application/json
Authorization: {{token}}

{
  "type": "debitCard"
}

### DELETE http://localhost:5000/api/v1/paymentMethod/:paymentMethodId eliminare un metodo di pagamento
DELETE {{endpoint}}/{{paymentMethodId}}
Authorization: {{token}}