@endpoint=http://localhost:5000/api/v1/transaction
@transactionId=66f4273f0dbcdd1ebeffb942
@numero=1000
@stringa=asdfgh
@data=2020-01-01
@categoryId=66f41df1a2013764123e3b8c
@paymentMethodId=66f419b544f6d7cf934206b2
@userId=66f40e032feb3bee2234e9df
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNDBlMDMyZmViM2JlZTIyMzRlOWRmIiwiaWF0IjoxNzI3MjcwNDAzLCJleHAiOjE3MjcyODEyMDN9.2eTeaQLNKK7kdfLnu__Kx0qpTw2ZaEdgIPlsilmkzNc

### GET http://localhost:5000/api/v1/transactions recuperare una o tutte le transazioni
GET {{endpoint}}
Authorization: {{token}}

### POST http://localhost:5000/api/v1/transaction creare una transazione
POST {{endpoint}}
Content-Type: application/json
Authorization: {{token}}

{
  "date": "{{data}}",
  "shop": "{{stringa}}",
  "address": "{{stringa}}",
  "description": "{{stringa}}",
  "amount": {{numero}},
  "category": "{{categoryId}}",
  "paymentMethod": "{{paymentMethodId}}",
  "user": "{{userId}}"
}

### PUT http://localhost:5000/api/v1/transaction/:transactionId modificare una transazione
PUT {{endpoint}}/{{transactionId}}
Content-Type: application/json
Authorization: {{token}}

{
  "date": "{{data}}",
  "shop": "{{stringa}}",
  "address": "{{stringa}}",
  "description": "{{stringa}}",
  "amount": {{numero}},
  "category": "{{categoryId}}",
  "paymentMethod": "{{paymentMethodId}}",
  "user": "{{userId}}"
}

### DELETE http://localhost:5000/api/v1/transaction/:transactionId eliminare una transazione
DELETE {{endpoint}}/{{transactionId}}
Authorization: {{token}}