@endpoint=http://localhost:5000/api/v1/user
@userId=66f52abc77d18cc5cc69166e
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjZmNTJhYmM3N2QxOGNjNWNjNjkxNjZlIiwiaWF0IjoxNzI3MzQ1ODY5LCJleHAiOjE3Mjc5NTA2Njl9.g5GghMyxFBKme5uvuzRcz3lwJzDDJ3C9hu9PT1Jrrig
@stringa=mjlt

### GET http://localhost:5000/api/v1/user/:userId recuperare un utente
GET {{endpoint}}/{{userId}}
Authorization: {{token}}

### PUT http://localhost:5000/api/v1/user/:userId modificare un utente
PUT {{endpoint}}/{{userId}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "{{stringa}}",
  "surname": "{{stringa}}",
  "email": "{{stringa}}@{{stringa}}.{{stringa}}",
  "password": "{{stringa}}{{stringa}}",
  "passwordConfirm": "{{stringa}}{{stringa}}",
  "verifiedAt": "2020-01-01"
}

### DELETE http://localhost:5000/api/v1/user/:userId eliminare un utente
DELETE {{endpoint}}/{{userId}}
Authorization: {{token}}